# Generated by Django 3.1.2 on 2021-04-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'verbose_name': '質問掲示板', 'verbose_name_plural': '質問掲示板'},
        ),
    ]
